### ISSUE TITLE
Support for DSL-AX82U pixelserv certificate

### ISSUE THREAD

**Issue by akulumbeg** [decoderman/amtm#13]
Hello! 

I am running the latest Merlin by @gnuton on a DSL-AX82U (not RT!). I am unable to create a pixelserv certificate for it, because it says the following:

![image](https://user-images.githubusercontent.com/19264137/140556810-2942261d-8c06-4e6e-a288-cb0088033793.png)

Could I ask you for help here? I used gnuton's DSL-AC68U fw before and it worked perfectly there, however I am aware that the AX modems/routers are built slightly differently (.trx vs .w), so I am wondering if this could work? Thanks!

**Comment by akulumbeg** [comment]
...could it be as easy as editing line 38 in the helper script file? :)

**Comment by decoderman** [comment]
This should work now, I have simplified the supported model list.
