### ISSUE TITLE
entware generic installer not using https

### ISSUE THREAD

**Issue by ar3thien** [decoderman/amtm#15]
entware generic.sh script is not pointing to https when downloading opkg binary.
also, /opt/etc/opkg.conf is not switching to https

I'm using amtm 3.2.3

in order to resolve that, I had to append the commands in bold under entware_setup.mod just after the step of downloading entware generic script. I'm on armv7sf-k2.6 for info.

wget --timeout=10 --tries=3 --retry-connrefused -qO - "$INST_URL" **| sed 's/http:/https:/g' | sed -e "41 i sed -i 's/http:/https:/g' /opt/etc/opkg.conf"** | sh

**Comment by decoderman** [comment]
I am aware that during the initial Entware setup the http protocol is used. You will find that after completion of this install process all further Entware actions use the https protocol.

However, I do find your approach very useful and will include it with the next release of amtm (and Diversion) if you are OK with it.
Thanks for contributing.
