### ISSUE TITLE
webui white page

### ISSUE THREAD

**Issue by malinkb** [decoderman/amtm#16]
the WebUI is enabled, but I can't access it on the pixelserv-tls server address. All I get is a blank insecure web page.

**Comment by decoderman** [comment]
What app are you talking about? amtm itself does not have a webui. There is nothing to see on the pixelserv-tls IP except its statistics page which can be accessed with https://<your pixelserv-tls IP>/servstats

**Comment by malinkb** [comment]
If I access the webui on http://<pixelserv-tls address> I just get a blank page. However, I just figured out I was doing it the wrong way. I didn't notice until now, but in the amtm cli-interface it says I need to type 192.168.0.2/servstats to se the serverstats. That does work.
