### ISSUE TITLE
post-mount is broken by amtm 4.2

### ISSUE THREAD

**Issue by Max33Verstappen** [decoderman/amtm#19]
- The "post-mount" is broken because of  `. /jffs/addons/amtm/mount-entware.mod # Added by amtm` added but "mount-entware.mod" not there and never getting downloaded, hence the execution interrupted.

- The "post-mount" gets modified every time "amtm" is executed as `sed -i '/^[[:space:]]*$/d' "$1"` in `t_f /jffs/scripts/post-mount` is applied on "post-mount", so the timestamp of the file keeps changing even no actual content is changed.
And removing blank lines without prompting is inappropriate as users may keep blank lines on purpose.

**Comment by decoderman** [comment]
Thanks for reporting. I can verify your findings, the extra test I built in in v4.2 is overzealous and overshoots its intended purpose. 
Will be fixed ASAP.

**Comment by Max33Verstappen** [comment]
The updates fixed the problems, but `t_f /jffs/scripts/post-mount` is still invoked when adding `. /jffs/addons/amtm/mount-entware.mod # Added by amtm` to the "post-mount", which means all the blank lines are wiped out during that process. Is that intentional?

**Comment by decoderman** [comment]
Yes and no. I‘ll explain when I actually fix the real underlaying problem.
This was just a hotfix to prevent further issues users may have.
Stand by, I’ll get after it ASAP.

**Comment by Max33Verstappen** [comment]
Sure. Not a big issue. The hotfix is relatively important as it'd prevent the entware from being mounted if users reboot the device and get confused somewhat.
