### ISSUE TITLE
Email module: curl sends the wrong EHLO string

### ISSUE THREAD

**Issue by tazio** [decoderman/amtm#22]
Currently, in the EHLO command starting the SMTP connection it is appended the filename. This causes any MTA to reject the connection if EHLO restrictions are in place, with error 504.

The problem is in this line:
https://github.com/decoderman/amtm/blob/b1623e8bdb337b2f4b56e64b9e150c8d3e98c15e/amtm_modules/email.mod#L285

It should be fixed with something like:
        /usr/sbin/curl -v --url $PROTOCOL://$SMTP:$PORT/$SMTP 
 The server fqdn would be used by curl in the EHLO command, correctly.

**Comment by decoderman** [comment]
Hi @tazio 
Thank you for your input and correction. It will be included in the next amtm release.

**Comment by decoderman** [comment]
Progress update: I released [Diversion 5.1.1 patch update](https://www.snbforums.com/threads/diversion-5-1-1-the-router-ad-blocker-march-02-2024.88244/page-25#post-895697) yesterday and included your modification. 
Next is amtm which I'm working on at the moment.

**Comment by decoderman** [comment]
With the release of amtm 4.4 just now this request is completed.
