### ISSUE TITLE
[request] disk check script notifications

### ISSUE THREAD

**Issue by SirFireNewt** [decoderman/amtm#23]
Currently it appears the `dc` disk check script checks on boot but only stores that as a local log, if the disk is dying it would be nice to get a notification if our disk is having issues

**Comment by decoderman** [comment]
Hi @SirFireNewt 
That sounds like a very good idea. I'll see how it can show a message in amtm and also send an email if the settings are configured.
Consider this part of the next release.
Thanks for the idea.

Best regards

**Comment by decoderman** [comment]
With the release of amtm 4.4 just now, this request is completed.
