### ISSUE TITLE
Module amtm.mod download failed

### ISSUE THREAD

**Issue by klcb2010** [decoderman/amtm#26]
Initializing amtm for first run

 Getting from fwupdate.asuswrt-merlin.net
 ! Module amtm.mod download failed
 ! using fallback server diversion.ch
 ! Module amtm.mod download failed

 All download attempts failed,
 exiting amtm now.

 Check that both domains properly resolve
 on this router:
 - fwupdate.asuswrt-merlin.net
 - diversion.ch

`klcb2010@GT-AX6000:/tmp/home/root# ping fwupdate.asuswrt-merlin.net
PING fwupdate.asuswrt-merlin.net (172.67.170.222): 56 data bytes
64 bytes from 172.67.170.222: seq=0 ttl=54 time=217.961 ms
64 bytes from 172.67.170.222: seq=1 ttl=54 time=210.875 ms
64 bytes from 172.67.170.222: seq=2 ttl=54 time=211.802 ms
^C
--- fwupdate.asuswrt-merlin.net ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 210.875/213.546/217.961 ms

klcb2010@GT-AX6000:/tmp/home/root# ping diversion.ch
PING diversion.ch (80.74.145.140): 56 data bytes
64 bytes from 80.74.145.140: seq=0 ttl=53 time=258.828 ms
64 bytes from 80.74.145.140: seq=2 ttl=53 time=261.673 ms
^C
--- diversion.ch ping statistics ---
3 packets transmitted, 2 packets received, 33% packet loss
round-trip min/avg/max = 258.828/260.250/261.673 ms`

![截屏图片 (1)](https://github.com/decoderman/amtm/assets/32628414/10c2ba7c-a273-4d76-9dcc-b3d62e93559f)

**Comment by decoderman** [comment]
That is your ISP/Resolver or network problem.
