### ISSUE TITLE
Firmware Update Notification: Support for GT-BE98 Pro

### ISSUE THREAD

**Issue by p1r473** [decoderman/amtm#27]
Hi, can you please add Support for GT-BE98 Pro for FW version update checker?
` Your firmware (102.1) does not support update notification. This feature was introduced in Asuswrt-Merlin 380.65. `
```
ASUS GT-BE98_Pro HW: aarch64 Kernel: 4.19.275 FW: 102.1_beta1.. 
```
However I am on latest 3006.102.1-beta 1

**Comment by decoderman** [comment]
Please wait until I have a Asuswrt-Merlin (Gnuton fork) firmware to test this on my GT-BE98 router as there is none available at this time. This is beta software and I will get to it when I am able to test it.

**Comment by p1r473** [comment]
Sure, thank you!

**Comment by p1r473** [comment]
By the way, it's out of beta now

**Comment by decoderman** [comment]
You can test it by force-updating amtm with uu.
