### ISSUE TITLE
Add gmail port 587 smtp to suggested settings

### ISSUE THREAD

**Issue by elp3dr0** [decoderman/amtm#31]
Guidance provided to the user in amtm_modules/email.mod suggests using gmail port 465.  "Gmail       smtp.gmail.com         465  smtps". AFAIK port 587 is regarded as more secure. Therefore recommend adding the following line:

Gmail       smtp.gmail.com         587  smtp

(note change in protocol too).

I can confirm these settings work for me.

**Comment by decoderman** [comment]
Will do that with the next update. Thanks
