### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by cloneman** [decoderman/amtm#7]
The script link in the Readme appears to be dead (redirects to regular web page)
https://diversion.ch/amtm/amtm

Workaround is using the github hosted url.

**Comment by decoderman** [comment]
> 
> 
> The script link in the Readme appears to be dead (redirects to regular web page)
> https://diversion.ch/amtm/amtm
> 
> Workaround is using the github hosted url.
That works as intended if you use it right.
Use the complete command, not just the URL part to install amtm, it'll work for scripts but not for a browser, hence the redirect to the website front page.
