### ISSUE TITLE
Let's encrypt support

### ISSUE THREAD

**Issue by doomfrawen** [decoderman/amtm#8]
Hi Team,

As you might be aware, the Acme client inside the routers no longer supports the creating/requests of certificates due to an updated API URI and methods. 

Would it be possible if it is not too much trouble to include support for le'ts encrypt?

#https://github.com/RMerl/asuswrt-merlin.ng/issues/373

**Comment by decoderman** [comment]
I will wait for Asus and Merlin's response before I take any action.
